name: CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  # Run our CI/CD builds.  We build a matrix with the various build targets
  # and their details.  Then we build either in a docker container (Linux)
  # or on the actual hosts (macOS, Windows).
  build:
    strategy:
      matrix:
        platform:
          # All builds: core platforms
          - name: "Linux (GCC)"
            id: linux-gcc
            os: ubuntu-latest
            setup-script: linux
            env:
              CC: gcc
              CMAKE_GENERATOR: Ninja
          - name: "Linux (Clang)"
            id: linux-clang
            os: ubuntu-latest
            setup-script: linux
            env:
              CC: clang
              CMAKE_GENERATOR: Ninja
          - name: "macOS"
            id: macos
            os: macos-12
            setup-script: macos
            env:
              CC: clang
              CMAKE_GENERATOR: Ninja
          - name: "Windows (x64, Visual Studio)"
            id: windows-amd64-vs
            os: windows-2019
            env:
              ARCH: amd64
              CMAKE_GENERATOR: Visual Studio 16 2019
          - name: "Windows (x86, Visual Studio)"
            id: windows-x86-vs
            os: windows-2019
            env:
              ARCH: x86
              CMAKE_GENERATOR: Visual Studio 16 2019
          - name: "Windows (amd64, mingw)"
            id: windows-amd64-mingw
            os: windows-2019
            env:
              ARCH: amd64
              CMAKE_GENERATOR: MinGW Makefiles
          - name: "Windows (x86, mingw)"
            id: windows-x86-mingw
            os: windows-2019
            env:
              ARCH: x86
              CMAKE_GENERATOR: MinGW Makefiles
      fail-fast: false
    env: ${{ matrix.platform.env }}
    runs-on: ${{ matrix.platform.os }}
    name: "Build: ${{ matrix.platform.name }}"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up build environment
        run: .github/setup/${{ matrix.platform.setup-script }}-build.sh
        if: matrix.platform.setup-script != ''
      - name: Build
        run: |
          cmake -S . -B build --fresh
          cmake --build build
